name: mmlspark
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - pyspark=3.0.1
  - requests
  - r-base
  - r-dplyr
  - r-sparklyr
  - r-devtools
  - pip:
    - wheel
    - sphinx
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
