name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11.8
  - requests=2.26.0
  - pip=21.3
  - r-base=4.1.1
  - r-sparklyr=1.8.1
  - r-devtools=2.4.2
  - cmake<=3.27
  - pip:
    - pyarrow==10.0.1
    - pyspark==3.4.1
    - pandas==1.4.0
    - wheel
    - sphinx==5.0.2
    - sphinx_paramlinks==0.5.2
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - nbformat
    - pyyaml
    - PyGithub
    - tqdm
    - ipython
    - pytest-codeblocks
    - azure-storage-blob
    - jupyter
    - twine
    - mlflow==2.21.3
    - numpy==1.26.4
    - torch==2.0.0
    - torchvision==0.15.1
    - horovod==0.28.1
    - petastorm==0.12.1
    - pytorch_lightning==1.5.0
    - onnxmltools==1.7.0
    - matplotlib==3.10.1
    - Pillow==11.2.1
    - transformers==4.49.0
    - huggingface-hub==0.26.0
    - langchain==0.0.152
    - openai==0.27.5
    - black==22.3.0
    - black[jupyter]==22.3.0
    - mistletoe
    - markdownify
    - pypandoc
    - traitlets
    - opencv-python==4.11.0.86
    - sentence_transformers==4.0.2
